version: '3.7'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  migration:
    build: .
    volumes:
      - ./server/db/migrations:/app/server/migrations
      - ./node_modules:/app/node_modules
      - ./server/node_modules:/app/server/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://dbuser:dbpass@postgres:5432/app
    command: ./wait-for-it.sh postgres:5432 -- yarn workspace server migrate up

volumes:
  db-data:
